### ISSUE TITLE
Allow to specify targets by DNS name

### ISSUE THREAD

**Issue by linki** [szuecs/kube-static-egress-controller#16]
Currently, I can define targets as IP or subnet CIDR to tell Kubernetes to route traffic through a NAT.

For cases where the target IPs/subnets can change but DNS does not it would be helpful to be able to specify targets via DNS directly.

**Comment by nebularazer** [comment]
This issue originated from a question i had.

My use case is googles smtp relay: smtp-relay.gmail.com
Which selects an IP at random from one of the networks listed in googles spf records (18 networks at the time of writing this)

as @linki mentioned to me i can add multiple networks in the data section, but this will only work until google adds a new IP / Net and the dns name will be resolved to that new IP address which is not covered by one of the egress ips/networks.

**Comment by szuecs** [comment]
@nebularazer Your use case might be good fit for the DNS case, because it seems not to be a very active route that needs to work all the time.

**Comment by szuecs** [comment]
Because of an internal discussion I update the issue.

This change can lead to production errors, if you expect it to work reliably. The DNS based static egress destination will only be switched slowly, because routing works on IP, not DNS and DNS is cached in all DNS server and clients, you do not have control.
If you need a target ELB to route traffic to with static egress, then please add an Elastic IP to the ELB, which means you have a static IP to route to as destination.
You always need a static IP destination to make this work reliably.

**Comment by linki** [comment]
Unfortunately, it's not possible to assign an Elastic IP to an ELB.

**Comment by linki** [comment]
My question would be: "Does this have to work 100% reliable?"

From my understanding the use case is the following: People want to set up an `egress` to an ELB endpoint. Since they have to use IPs they figure them out manually once and specify them in the CRD. Now that becomes a ticking timebomb as AWS is going to change those IPs at any point. Some time in the future alerts will fire, people wake up and update CRDs with the new IPs to fix it...

If `egress-controller` implemented this feature the problem would be fixed automatically and faster than any human. Otherwise we should emphasize that setting up `egress` rules to ELBs is highly discouraged and people should find other solutions.

**Comment by szuecs** [comment]
@linki of course this is **highly discouraged**!!
As I wrote in [my comment](https://github.com/szuecs/kube-static-egress-controller/issues/16#issuecomment-423957089).

Routing is layer 3 based on IP, not DNS the solution provides a routing feature. I don't want to provide a tool that unexperienced users will shoot themselves in their food.

**Comment by kgalli** [comment]
@szuecs I understand the downside which comes with relying on DNS which might confuse so-called `inexperienced` users. But what do you think about somebody who understands the impact?

Imagine that you control your infrastructure but you can not control the infrastructure of your third party you connect to. Now the expected static IP is changing without any further notification.

With DNS it would fail but eventually heal itself after the cache gets cleared (you might be able to minimize DNS cache on your side as you have your infrastructure under control).

Without DNS your service which relies on the third party will fail and only human interaction can fix it. 
I do see a big benefit here. So what is the balance between an `inexperienced` and an `experienced` user?

Maybe there is a solution for both?
