### ISSUE TITLE
Detect failing cloudformation stack

### ISSUE THREAD

**Issue by mikkeloscar** [szuecs/kube-static-egress-controller#7]
In case the cloudformation stack creation fails i.e. because the EIP limit is reached the controller doesn't detect this and recreate the cloudformation stack.

The controller should have some kind of sync interval to ensure that the cloudformation stack is created with the correct IPs and log an appropriate error if it's not able to create the cloudformation stack.

**Comment by szuecs** [comment]
@njuettner the retry is nice, but it does not fix completely this issue. We have basically to resync our "known" state. Resync means here calling Update() and if this fails with an error that "stack does not exist" do a Create(). This should also be done in initSync() https://github.com/szuecs/kube-static-egress-controller/blob/master/main.go#L190 .
